Add throttle page
FAForever/faf-user-service pull request #8
Opened 2021-07-18 16:29 UTC by Sheikah45

2021-07-19 10:07 UTC, Brutus5000 requested changes

2021-07-19 22:17 UTC, Brutus5000 requested changes

2021-07-19 22:17 UTC, Brutus5000 commented on src/main/kotlin/com/faforever/userservice/config/SecurityConfiguration.kt
> +                authorize("/throttle", permitAll)
obsolete now?

2021-07-19 22:41 UTC, Sheikah45 commented on src/main/kotlin/com/faforever/userservice/config/SecurityConfiguration.kt
> +                authorize("/throttle", permitAll)
correct

2021-07-20 19:41 UTC, Brutus5000 approved these changes

2021-07-20 19:42 UTC, merged